management:
  security:  
    enabled: false  
    
spring:
  application:
    name: builder
  
  jackson:
   serialization:
     write_dates_as_timestamps: false   
  
  banner:
    location: classpath:/banner.txt
    
imast:
  shoc:
    database:
      uri: ${SHOCDB_URI:mongodb://shoc:shoc@localhost:11001/?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&authSource=admin}
      db: ${SHOCDB_DB:shocdb}
          
server:
  port: 11002
  connection-timeout: 900000
  http2:
      enabled: true
  compression:
      enabled: true
      mime-types: application/json
  