version: '3.5'

volumes: 
  dind-data-volume:
  shocdb-data-volume:
  shocdb-logs-volume:
  docker-registry-volume:  

networks:
  shoc-network:
    name: shoc-network

services:   
  
  shocdb:
    image: shocdb:latest
    restart: always
    build: ./shocdb
    container_name: shocdb
    env_file: ./env/mongo.env
    ports:
      - '11001:11001'
    networks:
      - shoc-network
    volumes:
      - shocdb-data-volume:/data/db
      - shocdb-logs-volume:/data/logs
      
  docker-registry:
    image: docker-registry:latest
    restart: always
    build: ./docker-registry
    container_name: docker-registry
    env_file: ./env/docker-registry.env
    ports:
      - '11004:11004'
    networks:
      - shoc-network
    volumes:
      - docker-registry-volume:/var/lib/registry

  dind:
    image: dind:latest
    build: ./dind
    restart: always
    container_name: dind
    privileged: true
    ports:
      - '11003:11003'
    networks:
      - shoc-network
    volumes:
      - dind-data-volume:/var/lib/docker

  builder:
    image: builder:latest
    restart: always
    build: ./builder
    container_name: builder
    env_file: ./env/api.env
    ports:
      - '11002:11002'
    networks:
      - shoc-network
   
